name: Publish
on:
  push:
    branches:
      - main # Edit this

jobs:
  publish:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: "root" # Edit this
          server: "142.93.225.202" # Edit this
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # Add this to secrets
          local_path: "./*"
          remote_path: "/root" # Edit this
